### ISSUE TITLE
DataSource.BaseStream.Position Exception Due to Small File Size

### ISSUE THREAD

**Issue by purplefarmer** [hotkidfamily/HexBox.WinUI#1]
![image](https://github.com/user-attachments/assets/353f044b-f368-4ae3-9773-5cbf17afed9d)

`
private static object CoerceOffset(DependencyObject d, object value)
{
	var HexBox = (HexBox)d;

	if (HexBox.DataSource != null)
	{
		long offset = (long)value;

		value = offset.Clamp(0, HexBox.DataSource.BaseStream.Length - 5*_MaxColumns);
	}
	else
	{
		value = 0L;
	}

	return value;
}
`

The following code can cause a negative value when the file size is too small:

`value = offset.Clamp(0, HexBox.DataSource.BaseStream.Length - 5*_MaxColumns);`

WPF HexView Code is as follows.
https://github.com/fjeremic/HexView.Wpf/blob/1421090257ec45bd7a01ac4b7793820620b42aa4/HexView.Wpf/HexViewer.cs#L1427 

`value = offset.Clamp(0, hexViewer.DataSource.BaseStream.Length);`

**Comment by hotkidfamily** [comment]
Thank you, it has been fixed, Please checkout.

**Comment by hotkidfamily** [comment]
Thank you, it has been fixed, Please checkout.
